#!/usr/bin/env bash

set -e

USER_CONFIG="user.conf.yaml"
ROOT_CONFIG="root.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${USER_CONFIG}" "${@}"
read -p "Run sudo configuration? [y/n] " choice
if [ ${choice:l} == "y" ]
then
    sudo "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${ROOT_CONFIG}" "${@}"
fi

