".config/zsh/powerlevel10k":
    type: "git-repo"
    clone-args: "--depth=1"
    url: "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod: "168h"

".config/zsh/zsh-autosuggestions":
    type: "git-repo"
    url: "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod: "168h"

".config/zsh/zsh-syntax-highlighting":
    type: "git-repo"
    url: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod: "168h"
