#!/usr/bin/env sh

# run sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# config
monitors=$(bspc query -M --names)
num_monitors=$(echo $monitors | wc -w)
case $num_monitors in
  1)
    bspc wm -O $monitors
    bspc monitor $monitors -d 1 2 3 4 5 
    ;;
  2)
    first=$(echo $monitors | cut -d " " -f 1)
    second=$(echo $monitors | cut -d " " -f 2)
    bspc wm -O $first $second
    bspc monitor $first -d 1 2 3 4 5
    bspc monitor $second -d 6 7 8 9 0
    ;;
  3)
    first=$(echo $monitors | cut -d " " -f 1)
    second=$(echo $monitors | cut -d " " -f 2)
    third=$(echo $monitors | cut -d " " -f 3)
    bspc wm -O $first $second $third
    bspc monitor $first -d 1 2 3
    bspc monitor $second -d 4 5 6
    bspc monitor $third -d 7 8 9
    ;;
esac

bspc config border_width           2
bspc config normal_border_color    "#89b4fa"
bspc config active_border_color    "#89b4fa"
bspc config focused_border_color   "#cba6f7"
bspc config presel-feedback_colour "#b4befe"

bspc config window_gap             10
bspc config -m eDP-1 top_padding   20

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# reset cursor theme
xsetroot -cursor_name left_ptr

# run xfce4 components
xfsettingsd --disable-wm-check --daemon &
xfce4-panel --disable-wm-check &
xfdesktop --disable-wm-check &
