#!/usr/bin/env sh

# run sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# config
bspc wm -O eDP-1 DP-2-2
bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor DP-2-2 -d 6 7 8 9 0

bspc config border_width           2
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config window_gap             10
bspc config -m eDP-1 top_padding   20

bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true

# rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# reset cursor theme
xsetroot -cursor_name left_ptr

# run xfce4 components
xfsettingsd --disable-wm-check --daemon &
xfce4-panel --disable-wm-check &
xfdesktop --disable-wm-check &
