theme = "nord"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
cursorline = true

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"
