#
# ~/.zshenv by chluna
#
# for `root` user, ln -s $HOME/.zshenv to /root
#

# zsh
export XDG_CONFIG_HOME=$HOME/.config
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# zsh history
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export HISTFILE=$ZDOTDIR/.zhistory
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_SAVE_NO_DUPS

# micro
export EDITOR="micro"
export MICRO_TRUECOLOR=1

# nnn
export NNN_BMS="o:~/OneDrive;e:/run/media/spike"
export NNN_USE_EDITOR=1
export NNN_COLORS=3421

# dotfiles folder
export DOTFILES=$XDG_CONFIG_HOME/dotfiles
