#
# ~/.zshenv by chluna
#
# for `root` user, ln -s $HOME/.zshenv to /root
#

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# zsh history
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export HISTFILE=$ZDOTDIR/.zhistory
setopt SHARE_HISTORY
setopt INC_APPEND_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_SAVE_NO_DUPS
